<div data-role="page"> 
	<div data-role="header">
		<h1>ZendFramework2-MobileStarterkit</h1>
		<a href="/user/login" class="ui-btn-right">Se connecter</a>
	</div> 
	<div data-role="content">
		<h3>Bienvenue !</h3>
		<p>
		ZendFramework2-MobileStarterkit permet de construire des applications pour le web mobile avec
		Zend Framework 2.0 et jQuery Mobile 1.0.
		</p>
		<h3>Documentation</h3>
		<ul data-role="listview" data-inset="true">
			<li><a href="http://packages.zendframework.com/">Zend Framework 2.0</a></li>
			<li><a href="http://jquerymobile.com/demos/1.0rc2/">jQuery Mobile 1.0</a></li>
		</ul>
		<h3>Sources GitHub</h3>
		<ul data-role="listview" data-inset="true">
			<li><a href="https://github.com/cderue/">ZendFramework2-MobileStarterkit</a></li>
		</ul>
	</div>
</div> 
